#
# This is only an example configuration. Please see the Rails
# documentation for more details.
#

development:
  adapter: postgresql
  database: ansuz_development
  username: root
  password:
  host: localhost
  
test:
  adapter: postgresql
  database: ansuz_test
  username: root
  password:
  host: localhost

production:
  adapter: postgresql
  database: ansuz_production
  username: root
  password:
  host: localhost
